- name: Create project root
  file:
    path: "{{ project_root }}"
    state: directory
  tags: always

- name: Clone frontend repository
  git:
    repo: "{{ frontend_repo }}"
    dest: "{{ project_root }}/frontend"
    version: HEAD
  tags: always

- name: Clone backend repository
  git:
    repo: "{{ backend_repo }}"
    dest: "{{ project_root }}/backend" 
    version: HEAD
  tags: always

- name: Clone devops repository
  git:
    repo: "{{ devops_repo }}"
    dest: "{{ project_root }}/DevOps"
    version: HEAD
  tags: always
