> ---
- name: Update package cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes
  tags: [docker, install]
  
- name: Install prerequisites for Docker
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
      - software-properties-common
    state: present
  become: yes
  tags: [docker, install]

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/gpg
    state: present
  become: yes
  tags: [docker, install]

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release}} stable"
    state: present
  become: yes
  tags: [docker, install]
  
- name: Install Docker packages
  apt: