frontend_repo: "https://github.com/untitled97/frontend.git"
backend_repo: "https://github.com/untitled97/backend.git"
devops_repo: "https://github.com/untitled97/DevOps.git"

frontend_version: "v2.0"
backend_version: "v2.0"

project_root: "/home/ikondratiev/projects"
compose_file: "/home/ikondratiev/projects/DevOps/docker-compose.yaml"
